Course_Management/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Course_Management.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        [Required, StringLength(50), Display(Name = "Course Title")]
        public string CourseTitle { get; set; }
        [Required, StringLength(2000), Display(Name = "Overview")]
        public string Overview { get; set; }
        [Required,ForeignKey("Category")]
        public int CategoryId { get; set; }
        [Required]
        public int Duration { get; set; }
        [Required]
        public int Quizes { get; set; }
        [Required]
        public int Assesments { get; set; }
        [Required,Column(TypeName ="money")]
        public decimal Cost { get; set; }
        public string Thumbnail { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
    }
}

Course_Management/ViewModels/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Course_Management.ViewModels
{
    public class CourseViewModel
    {
        public int CourseId { get; set; }
        [Required, StringLength(50), Display(Name = "Course Title")]
        public string CourseTitle { get; set; }
        [Required, StringLength(2000), Display(Name = "Overview"),DataType(DataType.MultilineText)]
        public string Overview { get; set; }
        [Required, ForeignKey("Category"), Display(Name = "Category")]
        public int CategoryId { get; set; }
        [Required]
        public int Duration { get; set; }
        [Required]
        public int Quizes { get; set; }
        [Required]
        public int Assesments { get; set; }
        [Required, Column(TypeName = "money")]
        public decimal Cost { get; set; }
        public string Thumbnail { get; set; }
        [Display(Name = "Thumbnail")]
        public HttpPostedFileBase Photo { get; set; }
    }
}

Course_Management/Controllers/CourseController.cs
using Course_Management.DataAccessLayer;
using Course_Management.Models;
using Course_Management.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Course_Management.Controllers
{
    public class CourseController : Controller
    {
        TrainingDB db = new TrainingDB();
        // GET: Course
        public ActionResult Index()
        {
            
            IEnumerable<Course> course = db.Courses.Include("Category").Include("Batches").ToList();
            return View(course);
        }

        public ActionResult Details(int id)
        {
            Course c = db.Courses.Include("Category").FirstOrDefault(x => x.CourseId == id);
            return View(c);
        }


        public ActionResult Create()
        {
            ViewBag.categories = new SelectList(db.Categories, "CategoryId", "CategoryTitle");
            return View();
        }

        [HttpPost]
        public ActionResult Create(CourseViewModel cvm)
        {

            if (ModelState.IsValid)
            {
                if (cvm.Photo!=null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(cvm.Photo.FileName);
                    string filepath = Path.Combine("Images", "CourseImages", filename);
                    cvm.Photo.SaveAs(Server.MapPath("~/" + filepath));
                    Course course = new Course
                    {
                        CourseTitle = cvm.CourseTitle,
                        Overview = cvm.Overview,
                        CategoryId = cvm.CategoryId,
                        Duration = cvm.Duration,
                        Quizes = cvm.Quizes,
                        Assesments = cvm.Assesments,
                        Cost = cvm.Cost,
                        Thumbnail = filepath
                    };
                    db.Courses.Add(course);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            return View();
        }
    }
}

Course_Management/Controllers/EnrollController.cs
using Course_Management.DataAccessLayer;
using Course_Management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Course_Management.Controllers
{
    public class EnrollController : Controller
    {
        TrainingDB db = new TrainingDB();

        // GET: Enroll
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Create(int bId,int tId)
        {
            var trainee = db.Trainees.FirstOrDefault(x => x.TraineeId == tId);
            var batch = db.Batches.FirstOrDefault(x => x.BatchId == bId);
            db.Enrollments.Add(new Enrollment { BatchId = bId, TraineeId = tId });
            db.SaveChanges();
            return RedirectToAction("Index","Course");
        }
    }
}

Course_Management/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Course_Management.DataAccessLayer;
using Course_Management.Models;

namespace Course_Management.Controllers
{
    public class SkillsController : Controller
    {
        private TrainingDB db = new TrainingDB();

        // GET: Skills
        public ActionResult Index()
        {
            return View(db.Skills.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SkillId,SkillTitle")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                db.Skills.Add(skill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(skill);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SkillId,SkillTitle")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(skill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(skill);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            db.Skills.Remove(skill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Course_Management/Views/Course/Create.cshtml
@model Course_Management.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
}
<div class="row">

</div>
@using (Html.BeginForm("Create", "Course", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="row z-depth-2">
    <h4 class="center">Add New Course</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="input-field col s12">
            @Html.EditorFor(model => model.CourseTitle)
            @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "red-text" })
            @Html.LabelFor(model => model.CourseTitle)
        </div>
    </div>
    <div class="row">
        <div class="input-field col s3">
            @Html.EditorFor(model => model.Duration)
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "red-text" })
            @Html.LabelFor(model => model.Duration)
        </div>
        <div class="input-field col s3">
            @Html.EditorFor(model => model.Assesments)
            @Html.ValidationMessageFor(model => model.Assesments, "", new { @class = "red-text" })
            @Html.LabelFor(model => model.Assesments)
        </div>
        <div class="input-field col s3">
            @Html.EditorFor(model => model.Quizes)
            @Html.ValidationMessageFor(model => model.Quizes, "", new { @class = "red-text" })
            @Html.LabelFor(model => model.Quizes)
        </div>
        <div class="input-field col s3">
            @Html.EditorFor(model => model.Cost)
            @Html.LabelFor(model => model.Cost)
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "red-text" })
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
            @Html.EditorFor(model => model.Overview)
            @Html.ValidationMessageFor(model => model.Overview, "", new { @class = "red-text" })
            @Html.LabelFor(model => model.Overview)
        </div>
    </div>
    <div class="row">
        <div class="input-field col s5">
            @Html.DropDownListFor(model => model.CategoryId, ViewBag.categories as SelectList,"Select Category")
            @Html.LabelFor(model => model.CategoryId)
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "red-text" })
        </div>
        <div class="input-field col s7">
            <div class="file-field input-field">
                <div class="btn">
                    <span>Browse</span>
                    @Html.TextBoxFor(model => model.Photo, new { type = "file" })
                </div>

                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="Choose a image to upload" />
                </div>
            </div>
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "red-text" })
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            @Html.ActionLink("Back to list", "Index", "Skills",new { area=""}, new { @class = "waves-effect waves-light btn teal lighten-1" })
            <input type="submit" value="Create" class="waves-effect waves-light btn teal lighten-1 right" />
        </div>
    </div>
</div>
}


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.datepicker').datepicker();
            $('select').formSelect();
    })
    </script>
}

Course_Management/Views/Course/Details.cshtml
@model Course_Management.Models.Course
@{
    ViewBag.Title = "Details";
}

<h4>@Model.CourseTitle</h4>
<div class="row">
    <div class="col s4">
        <p>@Model.Category.CategoryTitle</p>
    </div>
    <div class="right">
        @if (Model.Cost == 0)
        {
            <span class="green-text">Free  </span>
        }
        else
        {
            <span>Tk.@Model.Cost  </span>
        }
        <a class="waves-effect waves-light teal lighten-1 btn" id="batch-btn">Take This Course</a>
    </div>
</div>

<div>
    <nav class="white">
        <div class="nav-wrapper">
            <ul>
                <li id="overview-li" class="active"><a id="overview-ancor" class="grey-text accent-4">OVERVIEW</a></li>
                <li id="features-li"><a id="features-ancor" class="grey-text accent-4">COURSE FEATURES</a></li>
                <li id="batch-li"><a id="batch-ancor" class="grey-text accent-4">UPCOMING BATCHES</a></li>
            </ul>
        </div>
    </nav>
    <div class="row z-depth-1">
        <div class="row" id="tab-overview">
            <div class="col s12">
                <p>@Model.Overview</p>
            </div>
        </div>
        <div class="row" id="tab-features">
            <div class="col s6">
                <p><strong>Duration :</strong><span class="badge">@Model.Duration</span></p>
                <hr />
                <p><strong>Assesments :</strong><span class="badge">@Model.Assesments</span></p>
                <hr />
                <p><strong>Quizes :</strong><span class="badge">@Model.Quizes</span></p>
            </div>
        </div>
        <div class="row" id="tab-batches">
            @if (Model.Batches.Count() > 0)
            {
                foreach (var item in Model.Batches)
                {
                    int seatleft = item.TraineeLimit - item.Enrollments.Count();
                    if (seatleft > 0 && DateTime.Now < item.StartDate)
                    {
                        <div class="col s6">
                            <div class="row">
                                <div class="col s10 offset-s1 z-depth-4">
                                    <h4 class="center grey">@item.BatchName</h4>
                                    <p><strong>Trainer :</strong><span class="badge">@item.Trainer.Name</span></p>
                                    <hr />
                                    <p><strong>StartDate :</strong><span class="badge">@item.StartDate.ToString("MMM dd, yyyy")</span></p>
                                    <hr />
                                    <p><strong>Seat Left:</strong><span class="badge">@seatleft</span></p>
                                    <hr />
                                    <p class="right">
                                        @Html.ActionLink("Enroll To This Batch", "Create", "Enroll", new { bId = item.BatchId, tId = 1 }, new { @class = "" })
                                    </p>
                                </div>

                            </div>
                        </div>
                    }
                }
            }
            else
            {
                <div class="col s12">
                    <h5>No Batches Scheduled Yet.</h5>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#tab-features").hide();
            $("#tab-batches").hide();
            $("#tab-overview").show();
            $("#overview-ancor").click(function () {
                $("#tab-features").hide(500);
                $("#tab-batches").hide(500);
                $("#tab-overview").show(500);
                $("#overview-li").addClass('active');
                $("#features-li").removeClass('active');
                $("#batch-li").removeClass('active');
            })
            $("#features-ancor").click(function () {
                $("#tab-overview").hide(500);
                $("#tab-batches").hide(500);
                $("#tab-features").show(500);
                $("#features-li").addClass('active');
                $("#overview-li").removeClass('active');
                $("#batch-li").removeClass('active');
            })
            $("#batch-ancor").click(function () {
                $("#tab-overview").hide(500);
                $("#tab-features").hide(500);
                $("#tab-batches").show(500);
                $("#batch-li").addClass('active');
                $("#features-li").removeClass('active');
                $("#overview-li").removeClass('active');
            })
            $("#batch-btn").click(function () {
                $("#tab-overview").hide(500);
                $("#tab-features").hide(500);
                $("#tab-batches").show(500);
                $("#batch-li").addClass('active');
                $("#features-li").removeClass('active');
                $("#overview-li").removeClass('active');
            })
        })
    </script>
}

Course_Management/Views/Course/Index.cshtml
@model IEnumerable<Course_Management.Models.Course>
@{
    ViewBag.Title = "Index";
}

<h2>Courses</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image">
                    <img src="@Url.Content(item.Thumbnail)" alt="@item.CourseTitle" class="myImage" />
                    <div class="middle">
                        @Html.ActionLink("READ MORE","Details","Course",new { id=item.CourseId},new { @class="teal lighten-1 white-text",style="padding:4px;"})
                    </div>
                    <a class="btn-floating halfway-fab waves-effect waves-light grey" style="overflow:no-display"><i class="material-icons">person</i></a>
                </div>
                <div class="card-content">
                    <p class="center flow-text"><strong>@item.CourseTitle</strong></p>
                </div>
                <div class="card-action">
                    <i class="material-icons">person</i><span> 1</span>
                    @if (item.Cost == 0)
                    {
                        <span class="right green-text">Free</span>
                    }
                    else
                    {
                        <span class="right">Tk.@item.Cost</span>
                    }

                </div>
            </div>
        </div>
    }
</div>