Course_Management/Models/Batch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Course_Management.Models
{
    public class Batch
    {
        public int BatchId { get; set; }
        [Required, StringLength(100), Display(Name = "Batch Name")]
        public string BatchName { get; set; }
        [Required,ForeignKey("Course")]
        public int CourseId { get; set; }
        [Required,ForeignKey("Trainer")]
        public int TrainerId { get; set; }
        [Required,Column(TypeName ="date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName ="date")]
        public DateTime? EndDate { get; set; }
        [Required, Display(Name = "Trainee Limit")]
        public int TraineeLimit { get; set; }
        public string Status { get; set; }
        public virtual Course Course { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

Course_Management/Controllers/BatchController.cs
using Course_Management.DataAccessLayer;
using Course_Management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Course_Management.Controllers
{
    public class BatchController : Controller
    {
        TrainingDB db = new TrainingDB();
        // GET: Batch
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult Create()
        {
            ViewBag.trainers =new SelectList(db.Trainers, "TrainerId", "Name");
            ViewBag.courses = new SelectList(db.Courses, "CourseId", "CourseTitle");

            return View();
        }


        [HttpPost]
        public ActionResult Create(Batch batch)
        {
            if (ModelState.IsValid)
            {
                db.Batches.Add(batch);
                db.SaveChanges();
            }
            ViewBag.trainers = new SelectList(db.Trainers, "TrainerId", "Name");
            ViewBag.courses = new SelectList(db.Courses, "CourseId", "CourseTitle");
            return View(batch);
        }
    }
}

Course_Management/Views/Batch/Create.cshtml
@model Course_Management.Models.Batch
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Batch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row z-depth-1">
        <h4 class="center">Add New Batch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "red-text" })
        <div class="row">
            <div class="input-field col s12">
                @Html.EditorFor(model => model.BatchName)
                @Html.ValidationMessageFor(model => model.BatchName, "", new { @class = "red-text" })
                @Html.LabelFor(model => model.BatchName)
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownListFor(model => model.CourseId, ViewBag.courses as SelectList, "Select Course")
                @Html.LabelFor(model => model.CourseId)
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "red-text" })
            </div>
            <div class="input-field col s6">
                @Html.DropDownListFor(model => model.TrainerId, ViewBag.trainers as SelectList, "Select Trainer")
                @Html.LabelFor(model => model.TrainerId)
                @Html.ValidationMessageFor(model => model.TrainerId, "", new { @class = "red-text" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                @Html.EditorFor(model => model.TraineeLimit)
                @Html.ValidationMessageFor(model => model.TraineeLimit, "", new { @class = "red-text" })
                @Html.LabelFor(model => model.TraineeLimit)
            </div>
            <div class="input-field col s6">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "datepicker", type = "text" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "red-text" })
                @Html.LabelFor(model => model.StartDate)
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                @Html.ActionLink("Back to list", "Index", "Batch",new { @class="waves-effect waves-light btn teal lighten-1"})
                <input type="submit" value="Create Batch" class="waves-effect waves-light btn teal lighten-1 right" />
            </div>
        </div>
    </div>

}
<div>
</div>
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.datepicker').datepicker();
            $('select').formSelect();
    })
    </script>
}